CREATE DATABASE hc4pontozero;
USE hc4pontozero;

DELIMITER $$

CREATE FUNCTION FNDELTATEMPO() 
RETURNS BIGINT
BEGIN
DECLARE DELTA_TEMPO BIGINT;
DECLARE TEMPO1 TIMESTAMP;
SET TEMPO1 = (SELECT TEMPO FROM tb_tm01_variaveis ORDER BY MEDICAO DESC LIMIT 1);
SET DELTA_TEMPO = TIMESTAMPDIFF(SECOND,TEMPO1, NOW());
RETURN DELTA_TEMPO;
END$$

CREATE FUNCTION FNDISPONIBILIDADE() 
RETURNS DECIMAL(6,2) 
BEGIN
DECLARE DISP DECIMAL(6,2);
DECLARE SOMAMULTIPLICACAO BIGINT;
DECLARE TEMPO_TOTAL BIGINT;
SET SOMAMULTIPLICACAO = (SELECT SUM(MULTIP) FROM TB_DISPONIBILIDADE);
SET TEMPO_TOTAL = (SELECT TEMPOTOTAL FROM TB_DISPONIBILIDADE ORDER BY TEMPO DESC LIMIT 1);
SET DISP = SOMAMULTIPLICACAO/TEMPO_TOTAL;
RETURN DISP;
END$$

CREATE FUNCTION FNMULTIPLICACAO() 
RETURNS BIGINT
BEGIN
DECLARE MULT BIGINT;
DECLARE MANUTENCAO BIGINT;
DECLARE SELECAO BIGINT;
SET SELECAO = (SELECT DELTATEMPO FROM TB_DISPONIBILIDADE ORDER BY ITEM DESC LIMIT 1);
SET MANUTENCAO = (SELECT MANUT FROM tb_tm01_variaveis ORDER BY MEDICAO DESC LIMIT 1);
SET MULT = SELECAO*MANUTENCAO;
RETURN MULT;
END$$

CREATE FUNCTION FNSOMAMULT() 
RETURNS BIGINT
BEGIN
DECLARE SOMAMULT BIGINT;
SET SOMAMULT = (SELECT SUM(MULTIP) FROM TB_DISPONIBILIDADE);
RETURN SOMAMULT;
END$$

CREATE FUNCTION FNTEMPOTOTAL()
RETURNS BIGINT
BEGIN
DECLARE TOTALTEMPO BIGINT;
SET TOTALTEMPO = (SELECT SUM(DELTATEMPO) FROM tb_disponibilidade);
RETURN TOTALTEMPO;                  
END$$

DELIMITER ;

CREATE TABLE tb_tm01_variaveis (
  MEDICAO bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TEMPO timestamp NULL DEFAULT current_timestamp(),
  TEMP float DEFAULT NULL,
  UMID float DEFAULT NULL,
  RPM smallint DEFAULT NULL,
  COR01 float DEFAULT NULL,
  COR02 float DEFAULT NULL,
  COR03 float DEFAULT NULL,
  COR04 float DEFAULT NULL,
  COR05 float DEFAULT NULL,
  COR06 float DEFAULT NULL,
  COR07 float DEFAULT NULL,
  COR08 float DEFAULT NULL,
  COR09 float DEFAULT NULL,
  OPER tinyint DEFAULT NULL,
  MANUT tinyint DEFAULT NULL
);

--INSERT INTO tb_tm01_variaveis (MEDICAO, TEMPO, TEMP, UMID, RPM, COR01, COR02, COR03, COR04, COR05, COR06, COR07, COR08, COR09, OPER, MANUT) VALUES
--(25, 50, 1250, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1),

CREATE TABLE tb_disponibilidade (
  TEMPO timestamp NULL DEFAULT current_timestamp(),
  ITEM bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
  MEDICAO2 bigint DEFAULT NULL,
  DELTATEMPO bigint DEFAULT 0,
  MULTIP bigint DEFAULT NULL,
  DISPONIBILIDADE decimal(6,3) DEFAULT 1.000,
  TEMPOTOTAL bigint DEFAULT NULL,
  KEY FKDISPONIBILIDADE(medicao2),
  CONSTRAINT FKDISPONIBILIDADE
  FOREIGN KEY(medicao2) REFERENCES tb_tm01_variaveis(medicao) ON DELETE SET NULL
);

--INSERT INTO tb_disponibilidade (TEMPO, ITEM, MEDICAO2, DELTATEMPO, MULTIP, DISPONIBILIDADE, TEMPOTOTAL) VALUES

--
-- Acionadores tb_tm01_variaveis
--
DELIMITER $$
CREATE TRIGGER TGDISPONIBILIDADE BEFORE INSERT ON tb_tm01_variaveis 
FOR EACH ROW 
BEGIN
INSERT INTO TB_DISPONIBILIDADE(
    TEMPOTOTAL,
    DELTATEMPO,
    MULTIP,
    DISPONIBILIDADE
    )
    VALUES(
        FNTEMPOTOTAL(),
        FNDELTATEMPO(),
        FNMULTIPLICACAO(),
        FNDISPONIBILIDADE()
        );
        END
$$
DELIMITER ;
